# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v0.2.0
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
advanced: true
classname: Hexchanting
generate_vscode: false
github_repo: hexchanting
github_user: arconyx
gradle_deps_type: gradle.properties
gradle_hex_version_key: hexcasting_version
gradle_mod_version_key: mod_version
main_branch: main
minecraft_version: 1.20.1
minecraft_version_in_mod_version: false
mod_description: Imbue tools with Hex Casting powers.
mod_display_name: Hexchanting
modid: hexchanting
multiloader: false
package_name: hexdoc-hexchanting
package_slug: hexdoc_hexchanting
pages_url: https://arconyx.github.io/hexchanting/
pattern_registry_path: main/kotlin/gay/thehivemind/hexchanting/casting/HexchantingPatterns.kt
source_url: https://github.com/arconyx/hexchanting
