# Default config file for Hexchanting

# If deleted this file will be regenerated on next launch.
# If this file cannot be loaded then default values will be used.
# If this file can be loaded but is invalid then loading will be halted and the game will crash.
# This is probably an error with your config, but if you are sure it isn't please open a bug.
# https://github.com/arconyx/hexchanting/issues

# Notes
# Boolean values accept 'true' or 'false' (no quotes, case-sensitive).

# Current config version. Don't touch this and don't remove it.
# Valid values: integer (default 1)
version = 1
